### PR TITLE
fix: resolve Short Channel Names overwriting all Click/Hover Events

### LINKED ISSUE #99: White Chat conflicts with Hypixel's name mention feature.

### PR DESCRIPTION
**Pull request by My-Name-Is-Jeff**
may help fix #99

### CODE REVIEW

File: src/main/java/club/sk1er/hytilities/handlers/chat/modules/modifiers/DefaultChatRestyler.java [hunk 1]
```diff
@@ -168,4 +169,25 @@ public void onMessageReceived(@NotNull ClientChatReceivedEvent event) {
...
+     * @param checkParentComponent Whether or not to check the parent chat component
+     */
+    private ChatComponentText shortenChannelName(IChatComponent message, String pattern, String replacement, boolean checkParentComponent) {
+        String originalText = message.getUnformattedTextForChat();
+        if (checkParentComponent && !originalText.contains("\u00a7")) {
+            originalText = (message.getChatStyle().getFormattingCode() + originalText + EnumChatFormatting.RESET).replaceAll(pattern, replacement);
+        }
+        ChatComponentText copy = (ChatComponentText) new ChatComponentText(originalText).setChatStyle(message.getChatStyle());
+        for (IChatComponent sibling : message.getSiblings()) {
+            copy.appendSibling(new ChatComponentText(sibling.getUnformattedTextForChat().replaceAll(pattern, replacement)).setChatStyle(sibling.getChatStyle()));
```
Comment (My-Name-Is-Jeff) [inline src/main/java/club/sk1er/hytilities/handlers/chat/modules/modifiers/DefaultChatRestyler.java:189]: Instead of using replaceAll, it may be possible to replace only one time since there is only one possible occurrence in an entire message?
