### PR TITLE
Fix White Chat and Private Messages overwriting all hover/click events

### LINKED ISSUE #99: White Chat conflicts with Hypixel's name mention feature.

### PR DESCRIPTION
**Pull request by My-Name-Is-Jeff**
may fix #99

### CODE REVIEW

File: src/main/java/club/sk1er/hytilities/handlers/chat/modules/modifiers/WhiteChat.java [hunk 1]
```diff
@@ -39,18 +37,22 @@ public int getPriority() {
...
         final String message = event.message.getFormattedText();
-        final List<IChatComponent> siblings = event.message.getSiblings();
-        boolean modified = false;
 
         if (HytilitiesConfig.whiteChat) {
             final Matcher matcher = getLanguage().whiteChatNonMessageRegex.matcher(message);
             if (matcher.find(0)) {
-                event.message = new ChatComponentText(matcher.group("prefix") + ": " + matcher.group("message"));
-                modified = true;
+                IChatComponent copy = event.message.createCopy();
```
Comment (My-Name-Is-Jeff) [inline src/main/java/club/sk1er/hytilities/handlers/chat/modules/modifiers/WhiteChat.java:44]: Might not even need a copy

**Comment by My-Name-Is-Jeff** [comment]
Fixing the Short Channel Names

**Comment by My-Name-Is-Jeff** [comment]
Actually I'll just make a separate PR since the other one is kind of broken
